app/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from werkzeug.security import generate_password_hash
from flask_login import UserMixin, LoginManager
from flask_marshmallow import Marshmallow
import uuid, secrets

db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key=True)
    email = db.Column(db.String(150), nullable=False)
    password = db.Column(db.String(150), nullable=False)
    token = db.Column(db.String, default='', unique=True)
    join_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    def __init__(self, email, password):
        self.id = str(uuid.uuid4())
        self.email = email
        self.password = self.set_password(password)
        self.token = self.set_token(32)

    def set_password(self, password):
        return generate_password_hash(password)

    def set_token(self, length):
        return secrets.token_hex(length)

    def __repr__(self):
        return f'Email: {self.email} added to Users'

class Venue(db.Model):
    id = db.Column(db.String, primary_key=True)
    price = db.Column(db.Numeric(precision=12, scale=2))
    location = db.Column(db.String(150), nullable=False)
    tags = db.relationship('Tag', backref='venue', lazy=True)
    user_token = db.Column(db.String, db.ForeignKey('user.token'), nullable=False)

    def __init__(self, price, location, user_token, tags=None):
        self.id = str(uuid.uuid4())
        self.price = price
        self.location = location
        self.user_token = user_token
        if tags:
            self.tags = [Tag(tag_name=tag, venue_id=self.id) for tag in tags]

    def __repr__(self):
        return f'Price: ${self.price} | Location: {self.location}'

class Tag(db.Model):
    id = db.Column(db.String, primary_key=True)
    tag_name = db.Column(db.String(50), nullable=False)
    venue_id = db.Column(db.String, db.ForeignKey('venue.id'), nullable=False)

    def __init__(self, tag_name, venue_id):
        self.id = str(uuid.uuid4())
        self.tag_name = tag_name
        self.venue_id = venue_id

class Event(db.Model):
    start_date = db.Column(db.Date, nullable=False)
    end_date = db.Column(db.Date, nullable=False)
    total_price = db.Column(db.Numeric(precision=10, scale=2))
    user_token = db.Column(db.String, db.ForeignKey('user.token'), nullable=False)

    def __init__(self, start_date, end_date, total_price, user_token):
        self.id = str(uuid.uuid4())
        self.start_date = start_date
        self.end_date = end_date
        self.total_price = total_price
        self.user_token = user_token

    def __repr__(self):
        return f'From {self.start_date} to {self.end_date} | Total Cost: ${self.total_price}'

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, Length, EqualTo

class RegisterForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Create Password:', validators=[DataRequired(), Length(min=3, max=40), EqualTo('confirm', message='The passwords must match.')])
    confirm = PasswordField('Confirm Password:', validators=[DataRequired(), EqualTo('password', message='The passwords must match.')])
    submit = SubmitField()

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField()

app/__init__.py
from flask import Flask
from config import Config
from flask_migrate import Migrate
from flask_cors import CORS

from .api.routes import api
from .auth.routes import auth
from .site.routes import site

from .helpers import JSONEncoder
from .models import db as root_db, login_manager, ma

app = Flask(__name__)

app.register_blueprint(api)
app.register_blueprint(auth)
app.register_blueprint(site)

app.config.from_object(Config)

root_db.init_app(app)
migrate = Migrate(app, root_db)

ma.init_app(app)
login_manager.init_app(app)
login_manager.login_view = 'auth.login'

app.json_encoder = JSONEncoder

CORS(app)

app/api/routes.py
from flask import Blueprint, request, jsonify
from ..helpers import token_required
from ..models import db, Venue, Event

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/api/venue', methods=['POST'])
@token_required
def save_venue(our_user):
    venue_data = request.json.get('venue_data')
    tags = request.json.get('tags', [])
    user_token = our_user.token
    saved_venue = Venue.save_venue(venue_data, tags, user_token)

    if saved_venue:
        return jsonify({'message': 'Venue saved successfully', 'venue': saved_venue}), 201
    else:
        return jsonify({'message': 'Failed to save venue'}), 400

app/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
        <script src="https://cdn.tailwindcss.com"></script>
        <title>Kekkonmi Backend</title>
    </head>
    <body class="bg-slate-800 text-slate-50 w-screen h-screen flex flex-col justify-center items-center">
        <div class="absolute top-4 text-3xl">Kekkonmi Backend</div>
        <nav class="absolute top-8 mt-8 flex gap-4">
            <a class="hover:underline" href="{{ url_for('site.home') }}">Home</a>
        {% if current_user.is_authenticated %}
            <a class="hover:underline" href="{{ url_for('auth.logout') }}">Log Out</a>
            <a class="hover:underline" href="{{ url_for('site.profile') }}">Profile</a>
        {% else %}
            <a class="hover:underline" href="{{ url_for('auth.register') }}">Register</a>
            <a class="hover:underline" href="{{ url_for('auth.login') }}">Log In</a>
        {% endif %}
        </nav>
        {% block content %}
        {% endblock content %}
    </body>
</html>

app/templates/login_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset id="email-field">
        {{ form.email.label }}
        <div class="text-slate-950">
            {{ form.email(placeholder='username@example.com') }}
        </div>
    </fieldset>
    <fieldset id="password-field">
        {{ form.password.label }}
        <div class="text-slate-950">
            {{ form.password(placeholder='Enter password') }}
        </div>
    </fieldset>
    <div class="text-center mt-8 rounded-full px-4 py-2 cursor-pointer hover:outline">
        {{ form.submit(value='Login') }}
    </div>
</form>

app/templates/register_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset id="email-field">
        {{ form.email.label }}
        <div class="text-slate-950">
            {{ form.email(placeholder='username@example.com') }}
        </div>
    </fieldset>
    <fieldset id="password-field" class="flex gap-4 mt-2">
        <div class="flex flex-col">
            {{ form.password.label }}
            <div class="text-slate-950">
                {{ form.password(placeholder='Enter password') }}
            </div>
        </div>
        <div class="flex flex-col">
            {{ form.confirm.label }}
            <div class="text-slate-950">
                {{ form.confirm(placeholder='Confirm password') }}
            </div>
        </div>
    </fieldset>
    <div class="text-center mt-8 rounded-full px-4 py-2 cursor-pointer hover:outline">
        {{ form.submit(value='Register') }}
    </div>
</form>